// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_DeviceInfo2_H
#define WINRT_DeviceInfo2_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.190730.2"), "Mismatched C++/WinRT headers.");
#include "winrt/impl/Microsoft.ReactNative.2.h"
#include "headers/DeviceInfo2.2.h"
namespace winrt::impl
{
    template <typename D>
    struct produce<D, DeviceInfo2::IReactPackageProvider> : produce_base<D, DeviceInfo2::IReactPackageProvider>
    {
    };
}
namespace winrt::DeviceInfo2
{
    inline ReactPackageProvider::ReactPackageProvider() :
        ReactPackageProvider(impl::call_factory<ReactPackageProvider>([](auto&& f) { return f.template ActivateInstance<ReactPackageProvider>(); }))
    {
    }
}
namespace std
{
    template<> struct hash<winrt::DeviceInfo2::IReactPackageProvider> : winrt::impl::hash_base {};
    template<> struct hash<winrt::DeviceInfo2::ReactPackageProvider> : winrt::impl::hash_base {};
}
#endif
