namespace DeviceInfo2
{
    runtimeclass SampleComponent
    {
        SampleComponent();
        String DeviceModel();
    };

    [default_interface]
    runtimeclass ReactPackageProvider : Microsoft.ReactNative.IReactPackageProvider
    {
        ReactPackageProvider();
    };

}
